# Generated by Django 3.1.11 on 2021-06-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210607_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
