# Generated by Django 3.1.11 on 2021-06-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_inventory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
    ]
