# Generated by Django 3.1.11 on 2021-05-25 08:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.wallet'),
        ),
    ]
