# Generated by Django 3.1.11 on 2021-06-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210602_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='money',
            new_name='balance',
        ),
    ]
